### ISSUE TITLE
Issue without reload

### ISSUE THREAD

**Issue by brandonparsons** [reagent-project/reagent#111]
Hi there,

I'm pretty much brand-new to CLJS and Reagent.  I'm trying to get started with the most basic of apps.

I'm running one of the auto-reloading templates out there. When I come fresh to the page, everything works perfectly! I can even click around and have different pages rendered by Reagent/React.

However, when I change a file in my project, the browser reloads the code, and I get an error which can only be solved by hard-refresh.

```
Figwheel: loaded these files
file_reloading.js:202 ("/js/out/myapp/core.js")
util.js:283 Uncaught Error: Invariant Violation: _registerComponent(...): Target container is not a DOM element.
ioc_helpers.js:89 Uncaught TypeError: Cannot read property 'style' of null
```

I don't suppose you could point me in the right direction?

**Comment by antishok** [comment]
It would help if you post your code, but my guess is you're rendering to the `<body>` element and not an inner element, that's caused similar problems for me. I worked around it by rendering to an inner element. 
I'm not sure but it seems this is being fixed in figwheel here: https://github.com/bhauman/lein-figwheel/issues/70

**Comment by mike-thompson-day8** [comment]
Can this issue be closed?

**Comment by brandonparsons** [comment]
Sure. I actually missed the notification from @antishok. I decided to wait a while on CLJS until the REPL ecosystem figures itself out
