### ISSUE TITLE
Reaction update behaviour

### ISSUE THREAD

**Issue by jaen** [reagent-project/reagent#116]
I've been led to understand that `reagent.ratom/reaction` memoises it's result and is recalculated only when any of ratoms in it's body changes value.
Observe the following code:

``` clojure
(let [atom     (reagent.core/atom nil)
      reaction (reagent.ratom/reaction (.log js/console "changed") @atom)]
  (defn test [new-val]
    (when-not (= @atom new-val)
      (.log js/console "updated")
      (reset! atom new-val))
    @reaction))
```

By my intuition (as described above) when you call it the function `test` with the same argument you should see `updated` and `changed` on the first call and no output on the other, but I get this spurious `change` message:

```
?> test("1-test-folder-1")
updated
change
=> "1-test-folder-1"
?> test("1-test-folder-1")
change
=> "1-test-folder-1"
```

Could it be a bug in reagent (and if so, how would should I narrow down the issue) or maybe there's something wrong with my intuition (it might be, since it's mostly reframe docs and some cursory source reading) or some other error on my part in which case additional documentation for posterity may come in handy.

**Comment by antishok** [comment]
Using `reagent.ratom/run!` instead of `reagent.ratom/reaction` will work.

`reagent.ratom/run!`'s docstring: `(run! & body)` "Runs body immediately, and runs again whenever atoms deferenced in the body change. Body should side effect."

It does the same as `reaction`, except that it enables an "auto-run" property of the created reaction.
I don't really know what the rationale is here.

**Comment by antishok** [comment]
Here's a related issue I've encountered with cursors:
```clojure
(def a (r/atom {:x "hi"}))
(def c (r/cursor a [:x]))

(add-watch c :k (fn [_ _ _ new-val] 
                  (print "c changed to: " new-val)))

(swap! a assoc-in [:x] "bye")
```
I'd expect this to print "c changed to: bye", but it doesn't print anything.

This happens (I think) because cursors work via reactions, and their reaction is also not marked as "auto-run" and so it never "runs" and doesn't capture changes in the original atom.

This only happens with cursors/reactions that are *not* derefed inside a render function. If it *is* derefed during a render, then reagent will "run" it properly anyway, even if it isn't marked "auto-run".
(When I say "run" I don't mean that the reaction's body is evaluated, I mean specifically `reagent.ratom/run` being called on the reaction)

**Comment by Deraen** [comment]
The reason for reaction being calculated again in the first message is that it is dereferenced outside the render loop or other reactions.

And the cursor problem: Working as expected.

Closing as this is old and as there doesn't seem to be any obvious problems here.
