### ISSUE TITLE
React Native Support

### ISSUE THREAD

**Issue by chadharrington** [reagent-project/reagent#119]
What is your thinking on supporting React Native?

We are big fans of Reagent (and re-frame) and would really like to use it in our iOS app as well as on the web. React Native now supports iOS and we'd love to throw away a ton of Objective-C and replace it with Clojure.

We may be able to help with the port, but wanted to get your thoughts on the direction.

Thanks for your great work on this excellent project.

**Comment by guruma** [comment]
does it means that using React Native mean we must know all the iOS Native things(NSString, UIApplication, RCTRootView... etc) ?

If then, i think, it is not any more web programming but a native programming. 

Is it cool?
It is a huge complexity. 

Simplicity matters.

**Comment by chadharrington** [comment]
@guruma,
I am not sure I understand your question. Are you asking why one would want to use React Native? If so, our reasons are as stated previously: we'd rather write Clojure than Objective-C. It also seems that you might be asking why native apps are better than web apps. If that is the case, our perspective is that native apps provide a far superior user experience than web or hybrid apps on mobile. This opinion is widely shared by many, including Facebook, which is why they developed React Native. 
Here is a good article covering the pros and cons of React Native: http://blog.scottlogic.com/2015/03/26/react-native-retrospective.html

You also might be asking if adding support for React Native to Reagent will make the framework more complex for non-native (web) users. Supporting React Native does not imply any change to the way Reagent works for web use cases. If you don't want to use React Native, you don't have to. 

Again, I likely misunderstood your question. I am happy to answer more clearly if needed. Best wishes.

**Comment by Gonzih** [comment]
Looks like current way of integrating something in to react native is to generate jsx code. Looks like JSX compiler is a big and important part of React Native.

**Comment by guruma** [comment]
@chadharrington,
I would like to appreciate of your answer that make my vague question clear. 
You drew out 3 questtions.

1. why one would want to use React Native?
2. why native apps are better than web apps?
3. will adding support for React Native to Reagent make the framework more complex for non-native (web) users?

I think that these questions are very worth to be answered on itself. And I wonder what people think about those.

From the holistic perspective, I think we are in the era of two paradigm shifts. One is FP, the other is HTML5.

It is difficult for me to admit that "native apps provide a far superior user experience than web or hybrid apps on mobile". Native apps is cooler than hybrid apps but...check out the slide below. It may change a little your thoughts.

http://www.slideshare.net/iivanoo/these-mobile-apps-will-let-you-totally-rethink-hybrid-app-development

And what about Chromium for mobile?
http://blog.chromium.org/2014/09/now-with-faster-dev-workflow-and-modern.html

Chrome is getting faster and faster.
https://www.youtube.com/watch?v=v0xRTEf-ytE#action=share

I should admit that IOS programmer who want to write in clojure can like React Native. And you said that "Supporting React Native does not imply any change to the way Reagent works for web use cases." But I'm a bit skeptic. I'm afraid that supporting React Native make it difficult to  maintain the simplicity of Reagent. (It is beyond my ability to explain the difficulty exactly. ;p)


p.s. I shouldn't forget that it is my duty as a reagent user to appreciate Reagent makers. 
Reagent is very simple. It can't be more simple. Thanks for a great job!

**Comment by Gonzih** [comment]
@guruma 
I think you are doing something wrong here man. We don't really question sanity of react native, we are asking how hard will it be to implement this support in reagent or something reagent-like-lookisg. Om support for react native is on it's way. I don't think that this issue is a place for discussion why React Native is good or bad idea. Can we focus more on question in place please? Thank you.

**Comment by guruma** [comment]
@Gonzih, 
Yeah. I see. 
I don't want to disturb you.

I had just wondered...
If it's a wrong direction, do we need to ask how hard a journey is in that direction?

Good Luck!

**Comment by VFe** [comment]
Very much in support of this!

**Comment by mfikes** [comment]
One issue that needs to be sorted is the ability to make use of the React Native JavaScript library from ClojureScript. React Native makes use of a special packager which combines application JavaScript/JSX with the React Native library, converting JSX to JavaScript, while making use of CommonJS to produce a single concatenated JavaScript artifact which is loaded into JavaScriptCore. 

An alternative approach that makes a lot of sense for ClojureScript is the ability to simply depend on React Native as a dependency (as Reagent does today with React.) An exploratory effort into the fundamentals needed to make this approach work is at https://github.com/swannodette/jsx-fun

**Comment by mfikes** [comment]
Also, this just-announced GSoC project will likely help with what I had mentioned in my previous comment. https://twitter.com/clojuregsoc/status/592782552705937409

**Comment by somlor** [comment]
I would love to see this. :+1:

**Comment by cvillecsteele** [comment]
+1

**Comment by mfikes** [comment]
For those interested, it just _might_ be possible to at least play around with React Native with Reagent, the reason being that React Native follows the React API. I bypassed the JSX/CommonJS issues using the *production* version of Om, and suspect the same may be true for Reagent. In other words, there _may_ actually be nothing that really needs to be done with Reagent in the end so it is worth trying :)

Here is how I did it with Om: https://github.com/omcljs/ambly/wiki/Driving-React-Native-with-Om

**Comment by marcloyal3** [comment]
Mike

Your are awesome!

Thank you.

m

**Comment by yayitswei** [comment]
Hi Mike, getting this error trying to build your clik-clak-joe reference project:

`Could not find artifact org.omcljs:ambly:jar:0.1.0-SNAPSHOT in clojars (https://clojars.org/repo/)`

**Comment by yayitswei** [comment]
Figured it out, here's my mirror: `[yayitswei/ambly "0.1.0-SNAPSHOT"]`

**Comment by mfikes** [comment]
@yayitswei `lein install` will make a local snapshot for you. I've updated the Ambly wiki.

**Comment by ruiyang** [comment]
+1 for supporting react native, if it is possible.

**Comment by huahaiy** [comment]
+1 
Would be great to have this.

**Comment by luposlip** [comment]
+1 from me too!

**Comment by murtaza52** [comment]
++1 !

**Comment by yayitswei** [comment]
:+1:++

**Comment by luposlip** [comment]
Ref #132 - which is a request for a curated Reagent Mobile UI Framework, which could be a viable alternative in _some_ use cases to React Native. But as I see it it's 2 completely different enhancement requests:

1. Enable generation of native code for iOS (later also Android) (this issue), and
2. Reagent Mobile UI Framework - a standardized way to generate hybrid mobile apps using Reagent

**Comment by mfrawley** [comment]
React native doesn't generate any native code, it's just pure JavaScript which interfaces with the Objective-C runtime via JavaScriptCore. NSHipster has a good article explaining this bridging 
http://nshipster.com/javascriptcore/
In addition they have developed a set of standard UI widgets that you can use out of the box but any native class can be exported to JS using the same technique. My understanding is what Reagent just wraps React, so in theory it should already work?

**Comment by luposlip** [comment]
Fair enough @mfrawley!

In my view these 2 issues are still related because of their end goal - making it easy to use Reagent for Mobile/Mobile UI development. If the rest of you disagree I'll remove the reference again.

**Comment by JulianLeviston** [comment]
Seems like this can be closed now.

**Comment by chendesheng** [comment]
Reagent can work with react native pretty well.
Here is a demo:  https://github.com/chendesheng/ReagentNativeDemo

**Comment by Gonzih** [comment]
Nice!

**Comment by mfikes** [comment]
@chendesheng That's awesome!

As an aside, @MNeise's GSoC work will lead to the ability for the ClojureScript compiler to consume CommonJS modules. This, along with the ability to plug in a JSX transform, will lead to an alternate approach where all of the code is expressed in terms of the Google Closure module system. This will fundamentally support REPL interaction (as the application code will not be embedded in a CommonJS closure), and it should allow for Google Closure DCE, code motion, etc., and it will make it easier to use other libraries from the ClojureScript ecosystem.

(For those asking, "What is Mike rambling on about?": @chendesheng's solution is simple and effective in that it embeds the ClojureScript runtime and application code as a CommonJS module in the output of the React Native packager. That works—I just wanted to share the current GSoC work and thinking for those who may have questions about the module systems and how they are used.)

**Comment by tahmidsadik112** [comment]
Awesome!

**Comment by chadharrington** [comment]
@mfikes Thanks for the explanation and all you are doing for the CLJS/iOS
ecosystem.

To help me understand the situation better, could you elaborate on:
1- What currently can't be done using @chengesheng's current solution
2- What will be able to be done that currently can't be done, once we have
@MNeise's work

Thanks for any light you can shed on these questions.

Chad Harrington
chad.harrington@gmail.com

**Comment by mfikes** [comment]
@chadharrington The two main things I see:
1. You can't use a REPL to redefine things at runtime, at least not in the conventional way ClojureScript REPLs operate. For example `reagentnative.core/page` is rendered in the JavaScript as a `reagentnative.core.page` _local_ JavaScript variable inside of a CommonJS closure, as opposed to being a top-level JavaScript global variable that can be replaced at runtime. (When you evaluate `(defn page [] ...)` in a REPL this sends JavaScript to be evaluated that involves `reagentnative.core.page = (function reagentnative$core$page(){...});`) To see that it is a local variable, look for `__d('AwesomeProject/reagentnative/main' ...` in the JavaScript, which you can see if you point a browser at `http://localhost:8081/reagentnative/main.bundle`, which is a defining function that wraps the ClojureScript runtime and application-generated JavaScript, essentially as a module employing a closure to isolate it.
2. Because the output isn't being sent through Google Closure, you probably can't get `:optimizations :advanced`, at least not across the entire JavaScript. (Perhaps it is possible to have `:advanced` output be placed in the CommonJS closure... that aspect is unclear to me.)

The general idea is that with @MNeise's work, libraries that are expressed as CommonJS modules will be transformed to be "flat" for consumption by the ClojureScript toolchain so that, instead of employing closures, they will employ mangled top-level names per the Google Closure dependency management system. The flat nature allows REPLs to work, and other live-reloading mechanisms such as @bhauman's Figwheel to replace code at runtime. Perhaps this will allow whole-program optimization, DCE, and other things that the Google Closure system affords (https://twitter.com/swannodette/status/607226719012036609). The philosophy is to convert JavaScript libraries employing other module systems to be Closure compatible (or, if lucky Closure optimizable), and then leverage all of the good Google Closure goodness from within the ClojureScript tooling system.

**Comment by AlwaysBCoding** [comment]
+1 I really want to see this.

There's a demo repo here: https://github.com/chendesheng/ReagentNativeDemo -- but it's really confusing and not explained very well. I'm not sure what exactly this person did to get Reagent to work with React Native and why. It seems that it's *possible* to get Reagent to work with React Native right now, but it's not explained anywhere on the internet how.

**Comment by AlwaysBCoding** [comment]
+1 I really want to see this.

I looked at the demo repo by @chendesheng -- https://github.com/chendesheng/ReagentNativeDemo -- but it's really confusing to understand what this person did. 

What exactly do you have to do to get Reagent to work with React Native? It seems like there's only 5 or 6 steps involved but what *are* those 5 or 6 steps. It's not explained very well anywhere on the internet.

**Comment by mfikes** [comment]
@AlwaysBCoding see http://blog.fikesfarm.com/posts/2015-07-20-reagent-react-native.html

**Comment by Gonzih** [comment]
I played a bit with reagent on react navite for android and I must say that some things needs to be done from the reagent side. First thing that I noticed is reagents optimization for inputs that is just not there for TextInput on reactnative. I'm not sure what exactly reagent does in the browser, but on mobile device it's not there, so input value updates are glitchy and slow. Not sure if it's possible to address this issue from outside of reagent code. Here small demo if you are interested in playing around: https://github.com/Gonzih/reagent-native. 

Any tips and suggestions are welcome!

**Comment by GetContented** [comment]
@Gonzih could be because recently a change was introduced for controlled text inputs. I don't really know if that's the case and I haven't examined it thoroughly... but it might be worth looking into : https://github.com/reagent-project/reagent/pull/126

**Comment by holmsand** [comment]
@Gonzih What you're seeing is probably that TextInput is a "controlled component" in React parlance. That means that it expects to be re-rendered with a new value immediately after onChange has fired, and if it doesn't get a new value, the input is reset to the old one.

That seems to be the case, according to: https://github.com/facebook/react-native/blob/master/Libraries/Components/TextInput/TextInput.js#L509

Reagent doesn't re-render immediately, of course, which is why it needs workarounds for input and textarea (otherwise you would lose keystrokes from time to time).

A possible simple workaround for your problem might be to call `(reagent.core/flush)` at the end of the onChangeText callback, to give React the behaviour it expects.

In the long run there should probably be some specialization for TextInput in React native as well, similar to the one for input/textarea here: https://github.com/reagent-project/reagent/blob/master/src/reagent/impl/template.cljs#L88

**Comment by Gonzih** [comment]
Yay! reagent.core/flush helped!
Thanks a lot, I will proceed with my experiments!

**Comment by jolby** [comment]
Can confirm that putting reagent.core/flush at the end of the on-change-text handler works great!

**Comment by drapanjanas** [comment]
Hi, I am trying to use reagent 0.6.0-alpha in React Native (0.19.0) application. But currently it seems not that straightforward (our discussion is [here](https://github.com/drapanjanas/re-natal/issues/14)), mainly because reagent.core depends on reagent.dom and reagent.dom.server, which requires corresponding modules.
Perhaps there is a plan already in the roadmap for decuopling reagent.core? Would be glad to contribute to make it happen.

**Comment by glittershark** [comment]
As an extra note, if you're using re-frame and you're dispatching db updates as a result of `TextInput.onTextChange` you should probably be using `dispatch-sync` instead of `dispatch`

**Comment by Deraen** [comment]
I'm closing this as I think Reagent works well enough with React-native nowadays.

Improvements in 1.0 and 1.1 have made it unnecessary to e.g. provide placeholder namespaces for react-dom.
