### ISSUE TITLE
render-component catch-rethrow loses the stack trace

### ISSUE THREAD

**Issue by Deraen** [reagent-project/reagent#120]
Hi,

When a component throws an exception because of some bad code the [render-component](https://github.com/reagent-project/reagent/blob/master/src/reagent/impl/util.cljs#L117-L127) catches the exception and rethrows it. Ideally the browser should display the original stack trace so that developer can see where the original problem was. Unfortunately for some reason Chrome seems to only display the error message, without the stack trace.

Here is a component using which I can reproduce this:
```
(defn error []
  [:p (aget nil "bar")])
```

What I would want to see and what I see if I comment out the catch block in `render-component`:
![foobar](https://www.dropbox.com/s/vrsrzp62aieg41p/Screenshot%20from%202015-04-09%2012%3A09%3A33.png?dl=1)
But with catch-rethrow only the first line is shown (without line number).

I've been trying to reproduce this without reagent, pure JS and CLJS, but I've been unable to do that. 

Here is a repository with three tests: https://github.com/Deraen/problems/tree/rethrow
You can try the tests from gh-pages, just open dev tools console and load one of these:
- http://deraen.github.io/problems/rethrow/reagent.html
- http://deraen.github.io/problems/rethrow/cljs-throw.html
- http://deraen.github.io/problems/rethrow/js-throw.html

**Comment by mike-thompson-day8** [comment]
Chrome Canary (Version 44.0.2394.3)  does correctly show the stack of re-thrown exceptions.  (I personally use Canary for all my dev work because I greedily want the latest features). 

But, as you point out, the current stable version of Chrome (Version 42.0.2311.135 for me) does not show the stack, and instead just shows the exception text itself, which is hopeless. 

Solutions:
   1.  Use Canary and you get nice stacks for free, now.
   2.  If you have to use Stable Chrome, then do this in your program somewhere (untested)
    ```
   (set! (.-onerror js/window)  #(.error js/console (.-stack %1)))
    ```

**Comment by Deraen** [comment]
I tested this with Chrome 44 and it does indeed work.

I guess it is a good idea to keep this open until 44 is promoted to stable.

**Comment by mike-thompson-day8** [comment]
Version 44 of Chrome is now stable.  So I'm going to close this.
