### ISSUE TITLE
reaction

### ISSUE THREAD

**Issue by zajac** [reagent-project/reagent#127]
I have more like a question than bug report. 
Can I just subscribe to some subscription without producing hiccup and messing up with React itself? All I want is to listen to some change in model and update some complicated JS component (CodeMirror). 
This will not work as I expected, body of reaction will not be executed:
```
(def a (reagent/atom 1))

(reaction
  (println "a is " @a))

(reset! a 2)
```
Thanks in advance.

**Comment by antishok** [comment]
I think this is the same (or related) issue/question as in https://github.com/reagent-project/reagent/issues/116

**Comment by mike-thompson-day8** [comment]
Yes, your use of `reaction` will work.  But when you are finished with the `reaction` you should `dispose` it. 

```
(def a (reagent/atom 1))

(def  x (reaction 
  (println "a is " @a))

;; later when you are done with x
(dispose x)
```

**Comment by zajac** [comment]
Yes, but it doesn't. Do you observe it working?
I'm not getting notification, thus println is not invoked.

**Comment by zajac** [comment]
BTW, where dispose is defined? what namespace?

**Comment by mike-thompson-day8** [comment]
Sorry, it is actually `dispose!`.  

It is part of the `IDisposable`  interface and is implemented for `Reaction`.  See [here](https://github.com/reagent-project/reagent/blob/19a384443f6353875cc4a0eef468e45f5411d2c5/src/reagent/ratom.cljs#L293-L304)

Hmm.  If you don't see it running, then perhaps do as @antishok suggested and use `run!` instead of `reaction`.   If still no luck, I'll have a look later.

**Comment by zajac** [comment]
Great! It's working now. Merci.
