### ISSUE TITLE
How do I maintain component state through a figwheel reload?

### ISSUE THREAD

**Issue by aaronjensen** [reagent-project/reagent#130]
With webpack/react hot loader and vanilla react, individual component state is maintained ([example](http://gaearon.github.io/react-hot-loader/)). I'm curious how I could go about getting that behavior with reagent.

Obviously, the reagent approach to component state doesn't work:

```clojure
(defn state-atom []
  (let [c (atom 0)]
    (fn []
      [:div {:on-click #(swap! c inc)} @c])))
```

But surprisingly, neither does this:

```clojure
(defn state-react []
  (reagent/create-class
    {:get-initial-state
     (fn [] {:count 0})

     :render
     (fn [this]
       [:div {:on-click #(reagent/replace-state this {:count (inc (:count (reagent/state this)))})}
        (:count (reagent/state this))])}))
```

Am I doing something wrong or is there not a way to do this right now? Thanks!

**Comment by aaronjensen** [comment]
@bhauman please feel free to chime in here if you've done this or could point me in the right direction.

**Comment by aaronjensen** [comment]
After doing some digging, it seems that something like https://github.com/gaearon/react-hot-api would be needed to make this work with react's state. Maybe there is another pattern I'm not aware of though.

**Comment by yogthos** [comment]
Figwheel allows making exceptions for what namespaces get reloaded as seen [here](https://github.com/bhauman/lein-figwheel#preventing-and-forcing-file-reloads). While it won't help keep local states, it can be useful for maintaining the global app state.

**Comment by mike-thompson-day8** [comment]
figwheel reloads typically involve a complete re-mount of all components. 

For example, see:
https://github.com/reagent-project/reagent-template/blob/46d28de0e5f8ad328c047333782d5bccf96f0457/src/leiningen/new/reagent/env/dev/cljs/reagent/dev.cljs#L9

followed by: 
https://github.com/reagent-project/reagent-template/blob/46d28de0e5f8ad328c047333782d5bccf96f0457/src/leiningen/new/reagent/src/cljs/reagent/core.cljs#L46-L47

I assume that's what you are doing.  In which case, any local atoms are lost because all the components are fully recreated, not just re-rendered. 

And so to your real question:  I'm not aware of a way to both alter the renderer **and** maintain local state.   On the other hand,  if you place your state in a central r/atom it is maintained across figwheel reloads. 

I'm going to close this because I'm on a mission to close a few issues, and because these sorts of questions should actually be asked in more general help forum like:
- http://clojurians.net/ (reagent channel)
- https://groups.google.com/forum/#!forum/reagent-project
- stackoverflow    (?)
