### ISSUE TITLE
selection/cursor position is not preserved across :content-editable 

### ISSUE THREAD

**Issue by chr15m** [reagent-project/reagent#220]
In an `[:input]` or `[:textarea]` box the cursor position is maintained across changes to the content of the box. This is not the case for a `[:div {:content-editable true}]` input.

Context: I am trying to implement a "smart input" textarea which has internally styled elements. For example, if the user types an email inside the box it is highlighted in red. Maybe there is some better way to do that than using `:content-editable`?

**Comment by metametadata** [comment]
Take a look at Facebook's rich text editor component: https://facebook.github.io/draft-js/

**Comment by chr15m** [comment]
@metametadata interesting, thanks!

**Comment by mike-thompson-day8** [comment]
@chr15m  I'm assuming you have found a workaround, and I'm going to close this.

**Comment by chr15m** [comment]
Thanks @mike-thompson-day8 yes I just ended up using a textarea and overlaying the UI elements I needed as indicators to the left side of the textarea in line with the text they were annotating. I made sure the font heights matched to ensure the indicator would line up with the line it was associated with.

**Comment by pavel-klavik** [comment]
Hi, I would love to see some solution for this since I am trying to create a rich text editor in Reagent. I don't want to use DraftJS since it introduces too much complexity and I would have to rewrite large chunks of it anyway.

What happens exactly. State of my component is updated and I know new selection/cursor position. I do rerendering and then in component-did-update, I am setting new position of cursor correctly. Afterwards, I will get onSelect event setting the offset to 0. Why is this happening?

I was trying to understand what is done in https://github.com/reagent-project/reagent/blob/master/src/reagent/impl/input.cljs, but I don't fully get the big picture.
