### ISSUE TITLE
Supporting controlled custom inputs components

### ISSUE THREAD

**Issue by madvas** [reagent-project/reagent#265]
Hi,

Speaking for all users of [cljs-react-material-ui](https://github.com/madvas/cljs-react-material-ui) with reagent. We hit the problem, that reagent's caret repositioning hack doesn't work for [TextField component](http://www.material-ui.com/#/components/text-field).

I prepared very simple demonstration [project](https://github.com/madvas/reagent-material-ui), which is basically fresh reagent template with cljs-react-material-ui. After bit of a hacking with reagent code, we figured out if we overwrite `reagent.impl.template/input-component?` like [this](https://github.com/madvas/reagent-material-ui/blob/4aba539b27bec2cde5d87ee3abc52dc43cea2fe0/src/cljs/reagent_material_ui/core.cljs#L16-L21) we can make repositioning work. That last condition is how to reliably identify TextField component, even after advanced optimisations. 

However this hack has undesired side-effect. We can no longer set value programmatically, only by typing with keyboard. As you can see [here](https://github.com/madvas/reagent-material-ui/blob/4aba539b27bec2cde5d87ee3abc52dc43cea2fe0/src/cljs/reagent_material_ui/core.cljs#L25-L25) if you uncomment line, you'll see value doesn't change for `ui/text-field`, but for `:input` it works ok. 

This way I'd like to kindly ask you for an advise how could we make repositioning for TextField work. I don't see too much into repositioning internals, not sure if we can somehow hack TextField component, or changes to Reagent will be needed.

Thank you very much

**Comment by Deraen** [comment]
#282 is merged and released as 0.8.0-alpha2

**Comment by metametadata** [comment]
Although I'm a bit late to the party as the fix is already merged, I have 2 concerns with it:

1) The new API isn't documented anywhere at the moment. The example of using the new hooks looks quite [scary](https://github.com/madvas/cljs-react-material-ui/issues/17#issuecomment-268807607).
2) I suspect there's a possibility to provide the universal solution without touching Reagent core and making the API much simpler, smt. like:

```clj
(def text-field (reagent-input-fixer/fix 
                              (r/adapt-react-class (aget js/MaterialUI "TextField"))))
```

This can be implemented as a new lib or as an utility function in Reagent.

The idea for the actual algorithm for fixing the jumps can be found in [my example for react-bootstrap](https://gist.github.com/metametadata/3b4e9d5d767dfdfe85ad7f3773696a60) and was also applied in [reagent-toolbox](https://github.com/dashmantech/reagent-toolbox/blob/3fd08cd79eb92216485407b4d29c0d6e9b5c51b4/src/cljs/reagent_toolbox/core.cljs#L121) (cc @pupeno). Essentially the fix boils down to catching `on-change` events and `force-update`-ing the component. Potential risks:
  * I haven't tested it with [cljs-react-material-ui](https://github.com/madvas/cljs-react-material-ui). @skuteli did you have any luck applying this solution to `cljs-react-material-ui`?
  * Browser support. I only tested the solution in Chrome and Firefox. It should be checked in IE.
  * Performance hit because of additional atom and function calls?

**Comment by Deraen** [comment]
I had to drop the synthetic-input feature from 0.8 as I could get it working in all cases (MaterialUI 0.19 worked with dirty tricks, MaterialUI 1 did not). I'll work on this for the next release. I'll add examples for the three most common projects (MaterialUI 0.19 and 1, React-boostrap) so it will be easy to ensure the fix will work in these cases.

**Comment by Deraen** [comment]
Solution has been found for Material-UI v1: https://github.com/reagent-project/reagent/blob/master/examples/material-ui/src/example/core.cljs

Seeing that I haven't seen or been able to find other proper solutions, I think other libs with similar problems should also provide property to replace the input component, so Reagent input component can be provided.
