### ISSUE TITLE
ReactDOMServer cannot be optimized away.

### ISSUE THREAD

**Issue by tomconnors** [reagent-project/reagent#274]
Because `reagent.core` requires `reagent.dom.server`, which loads `cljsjs.react.dom.server`, ReactDOMServer cannot be eliminated with closure advanced optimizations, even if `render-to-string` and `render-to-static-markup` are never called. The easiest solution would be to remove the `render-to-string` and `render-to-static-markup` aliases and the `reagent.dom.server` :require  from `reagent.core`. I'm not aware of any other solution.

**Comment by tomconnors** [comment]
Since I'm looking at the compilation output right now, thought I'd add that force-update-all also cannot be optimized away because of the ^:export. I assume there's a good reason for that ^:export?

**Comment by Deraen** [comment]
Closure optimization wont touch ReactDOMServer because it is inside foreign library, and those can only be dropped per namespace basis. (If `cljsjs.react.dom.server` is not required, react-dom-server.inc.js is not included). Previously react-dom-server code was loaded in react.inc.js anyways, but since 15.4.0 it is separated to its own file.

Related: https://github.com/reagent-project/reagent/issues/275
and fix: https://github.com/reagent-project/reagent/issues/276

**Comment by Deraen** [comment]
Should be fixed in 0.6.1.
