### ISSUE TITLE
Document how to use React Transition Group with Reagent

### ISSUE THREAD

**Issue by AlexanderWingard** [reagent-project/reagent#311]
I've been trying to integrate [react-transition-group](https://github.com/reactjs/react-transition-group) with reagent to create chained transitions.
It adds new lifecycle callbacks that should ideally be able to be set up using the reagenty way:

```clojure
(reagent.core/create-class 
  {:reagent-render [:div "Component"]
   :component-will-appear (fn [cb] (cb))
   :component-will-enter (fn [cb] (cb))
  }
```
However I never see these being called. If I set these callbacks using the react properties directly it works. Here is a working example: [reagent-with-transition-group-example](https://github.com/AlexanderWingard/reagent-with-transition-group-example)

This is a followup on the discussion in #55

**Comment by Deraen** [comment]
It will probably be a good idea to add dev-dependency on react-transition-group on Reagent, and add some samples and tests for this.

**Comment by Reefersleep** [comment]
@Deraen are anyone working on this issue, do you know? Or does anyone have an idea of why it doesn't work?

**Comment by Deraen** [comment]
I'm not sure, but I think the problem is that these lifecycle methods only work on direct children of TransitionGroup. And using Reagent component creates one additional component before the component created using create-class:

![image](https://user-images.githubusercontent.com/648087/30005872-974dc212-90f4-11e7-8a80-6b95f18bbf5f.png)

Didn't think a lot on how this could be solved, as I think the best solution will be to use React-transition-group 2 which removes these lifecycle methods and provides better API. Packaging that to Cljsjs now.

**Comment by Deraen** [comment]
Example here using the new react-transition-group 2: http://metosin.github.io/komponentit/#!/example.transitions
Code here: https://github.com/metosin/komponentit/blob/master/example-src/cljs/example/transitions.cljs#L34-L49

Even with the new API, there is the same problem that Reagent creates additional components if a function is used, which breaks TransitionGroup, but with this API it is possible to create the Transitions in for loop, and avoid the problem.

**Comment by Reefersleep** [comment]
Brilliant find! :+1: Guess it makes sense for react-transition-group 2 to identify its children as by looking directly beneath itself.

If you call a component function (with `()` rather than with `[]`) does `reagent` then also create the extra component? Maybe this would be an acceptable hack. Unsure of whether there are reasons not to call component functions directly.

**Comment by Deraen** [comment]
Yes, invoking a function, instead of creating a component, does work. Though in that case you need to move key metadata inside the function (not quite sure why...).

**Comment by Reefersleep** [comment]
Hack upon hack :D But still, it works! I wonder if the react team would have incentive to change the API to identify children in a different manner.

**Comment by Deraen** [comment]
I doubt TransitionGroup can be changed. It is currently really only mapping through list of children, adding some props to then, and doing this is any recursive way would be crazy complicated, and probably break other things.
