### ISSUE TITLE
TodoMVC example does not follow spec on items edited to be blank.

### ISSUE THREAD

**Issue by kennytilton** [reagent-project/reagent#315]
This is using a fresh today clone of Reagent and involves the TodoMVC example, both at version 0.6.0, and presumes the TodoMVC example is intended to follow the [spec](https://github.com/tastejs/todomvc/blob/master/app-spec.md). If that presumption is correct, it seems one detail was missed

> If it's empty the todo should instead be destroyed. 

Note that this is not a Reagent bug: the TodoMVC code re-uses the save logic of an original input, which simply ignores blank items. In the case of editing an existing item it should be deleted.

**Comment by gadfly361** [comment]
@kennytilton Thanks for the feedback!

The TodoMVC example in this repo falls short on a few of the specs. However, I don't think most TodoMVC examples that are included in a repo aim to meet the TodoMVC specs completely (here is a list of examples in [clojurescript](https://github.com/gadfly361/cljs-todomvc)). Instead, I think they aim to give a healthy approximation of the specs and to provide a familiar example.

Reagent does have an [example in the official TodoMVC repo](https://github.com/tastejs/todomvc/tree/master/examples/reagent) that met all of the specs at the time of writing. As an aside, a bug got overlooked when it was accepted (for some reason I used display "inline" somewhere).  That example could use an update to meet the newest specs and html structure provided by TodoMVC.  If I find some time, I will look in to updating it, but going to close this issue here.
