### ISSUE TITLE
the 'r/atom' not support nest, why?

### ISSUE THREAD

**Issue by damon-kwok** [reagent-project/reagent#334]
**Source:**
(defonce infos (atom {:a (atom "aaa") :b (atom "bbb") :c (atom "ccc")}))
   (for [info @infos]
     [:label @info])

**Error:** 
No protocol method IDeref.-deref defined for type cljs.core/PersistentVector: [:a #<Atom: "aaa">]

**Comment by Deraen** [comment]
You are looping over keyvalue pairs, `info` is e.g. `[:a (atom "aaa")]` instead of a atom, so you can't deref it.

Try:
```
(for [[key info] @infos]
   [:label @info])
```

You will also probably see two other warnings: deref can't be used in lazy operations (`for`), to fix this you can wrap `for` in `doall`. And warning about missing React key from sequence of elements, you can add `{:key key}` to the `:label` props map to use map key as React key.
