### ISSUE TITLE
`with-let` values evaluated more than once

### ISSUE THREAD

**Issue by zalky** [reagent-project/reagent#378]
Based on the documentation, I would have thought that the following are equivalent:

```clj
(defn component
  []
  (let [_ (do-something)]
    (fn []
      [:div ...])))

(defn component
  []
  (with-let [_ (do-something)]
    [:div ...]))
```

However, they behave differently when live reloading code during development. With the first, `(do-something)` is only ever evaluated once during the lifetime of the component. With the second, `(do-something)` is evaluated multiple times when code is live reloaded, even though no new components have been created. The `finally` clause is also evaluated multiple times during the lifetime of the component.

Is this expected behaviour?

**Comment by pesterhazy** [comment]
Interesting point. I was puzzling over `with-let`'s behavior as well.

Can you elaborate why you expect `do-something` to be evaluated only once?

When I looked at the macro implementation, I discovered that my mental model for `with-let` was wrong. I assumed incorrectly that with-let is implemented internally as a form-2 component. Instead, it turns out to create a form-1 component (no lifecycle methods, no "outer" function). The only-once behavior is implemented using a ratom through some magic that frankly I don't quite grok.

**Comment by zalky** [comment]
@pesterhazy , thanks for the response. Coming back to this problem after some time away, I'm a bit stumped because I can't seem to reproduce the issue that I saw before. For now, the `with-let` appears to be behaving as I would expect, like a form-2 or form-3 component.

I'm also foggy on the magic of `with-let`. Best I can tell the values in the binding are implemented as an array inside a cached reaction, [set only once here](https://github.com/reagent-project/reagent/blob/master/src/reagent/ratom.clj#L29-L31). The finally clause is in the `:on-dispose` of the reaction, and the reaction is cached in the reactive context of the component. I'm guessing that when the component is unmounted and the reaction is no longer watched, the `:on-dispose`is triggered and the finally block is evaluated. For this reason I would have thought that `with-let`, though not implemented with a form-2 component, is tied to the react lifecycle of the component in the same way.

I'm going to close this issue for now, unless I encounter this behaviour again.
