### ISSUE TITLE
having :on-change and :value defined in an input breaks on firefox 61 on android

### ISSUE THREAD

**Issue by sveri** [reagent-project/reagent#388]
Hi, 

I am not sure if this is a reagent issue or not, but have not found any meaningful discussion on this.
When I define a simple input like this:

    (def local-state (r/atom {}))
    [:input {:on-change   #(reset! local-state {:name (h/get-value-of-event %)}) :value (get @local-state :name "")}]

And open the page on my mobile firefox, try to enter something, the input gets filled with autocorrect suggestions after starting to enter some text.
It does not happen or desktop firefox or google chrome on my mobile.

Is this something that could be fixed in reagent at all? Is it a firefox problem? Is it an android problem?

**Comment by bitkiller42** [comment]
Same problem here.
Works on mobile chrome but not on firefox.

**Comment by bitkiller42** [comment]
Hi again, just looked at my code after coming back from work and voilà.
What works for me was to **remove :value** and let the TextField (from material-ui) manage it's state.

But i'haven't understood why the former version has worked on safari (mobile+desktop), chromium (mobile+desktop) and firefox (desktop) but not on firefox (mobile 65.0).

**Comment by Deraen** [comment]
MaterialUI problems aren't related to the original report and issues with that are known and workarounds are documented.

I tested basic DOM input on Firefox for Android (version 68) and at least the inputs on Reagent homepage without problems. Though autocomplete suggestions could depend on browser state, but  if there is problems with autocomplete that shouldn't be due to Reagent. Autocomplete can be disabled with `autocomplete="off"` attribute.
