### ISSUE TITLE
Some object properties can't be renamed by closure

### ISSUE THREAD

**Issue by tomconnors** [reagent-project/reagent#417]
Looking through an advanced-compiled script, I came across some property names from reagent that closure didn't rename. cljsRatom, cljsIsDirty, cljsDomValue, cljsInputDirty, cljsRenderedValue, cljsInputLive, cljsReactClass, perhaps others. I think this is because of the `$` and `$!` interop macros - those produce `object["key"]` style property access but for those names I think renaming the property is safe and `object.key` style access should be used instead.

**Comment by Deraen** [comment]
I've worked on this previously: https://github.com/reagent-project/reagent/pull/325

**Comment by tomconnors** [comment]
Tested with 0.9.0-SNAPSHOT and most of those names are now getting mangled. The only one I'm still seeing is cljsRatom. Thanks!

**Comment by Deraen** [comment]
I have added a TODO comment about cljsRatom: https://github.com/reagent-project/reagent/blob/88e9833be9c3135548d760286ffd84d88a0a0489/src/reagent/impl/component.cljs#L150

It will require some Reaction code refactoring because currently the key is passed in as a parameter, so proper interop can't be used.

**Comment by Deraen** [comment]
Should be mostly fixed in 0.9.
