### ISSUE TITLE
0.9.0-rc1 TypeError: Cannot read property '$argv$' of undefined

### ISSUE THREAD

**Issue by kwladyka** [reagent-project/reagent#460]
This happening when compile with `:advanced`. It works during developing `clj -A:fig:build`, because no `:advanced` compilation.

Reagent version:
`reagent {:mvn/version "0.9.0-rc1" :exclusions [cljsjs/react cljsjs/react-dom]}`

It works with:
`reagent {:mvn/version "0.8.1" :exclusions [cljsjs/react cljsjs/react-dom]}`

![image](https://user-images.githubusercontent.com/3903726/67512803-e42b8f80-f699-11e9-891f-452dd7a19d71.png)

Error:
```
git clone -b doc git@github.com:kwladyka/form-validator-cljs.git doc
cd doc
git checkout a81d4bc574cbab68e67a791db118e44f373e3217
# add `:pseudo-names true` to `dev.cljs.edn`
npm i
npx webpack --mode=production
clojure -A:fig:min
cp resources/public/index.html target/public/
cp -r resources/public/css target/public/
```

Then open `target/public/index.html` to see the issue.

Temporary solution: downgrade Reagent to `0.8.1`

**Comment by Deraen** [comment]
While this is a real problem, this is also related to the build setup. I've tested advanced build with lein-figwheel but not figwheel-main and webpack. I wonder if this setup uses extern files? `argv` property itself is only used by Reagent so that can be renamed, but problem that `props` name is also renamed. That property is from React and is mentioned in React extern files so it should not have been renamed.

**Comment by kwladyka** [comment]
Node dependencies:
https://github.com/kwladyka/form-validator-cljs/blob/doc/src/js/index.js

It is very simple project, take a look https://github.com/kwladyka/form-validator-cljs/tree/doc

**Comment by scramjet** [comment]
Just hit this myself. Using the unreleased `infer-externs` branch as a workaround for now. Will await an official rc3.
