### ISSUE TITLE
[0.9.0-rc2] child subscriptions are still run on unmount

### ISSUE THREAD

**Issue by Lokeh** [reagent-project/reagent#462]
This isn't confirmed yet, but we recently had to revert to 0.8.1 after trying 0.9.0-rc2 due to a bug where subscriptions to re-frame events were being run when the change to the data should have caused the children to be unmounted.

I hope to have time soon to create a minimal repo, but in the mean time I wanted to record it here in case others were experiencing the same issue and/or wanted to investigate.

**Comment by Deraen** [comment]
Did you notice this in development or production build or both? (If only production build, which build tool do you use?)

I guess you were using `@(re/subscribe [::foo])` forms to watch for subscriptions values? The implementation uses `reagent.ratom/add-on-disponse!`. This method wasn't changed in 0.9 but there are other places in RAtom which were changed, mostly related to refactoring aget/aset uses.

**Comment by Lokeh** [comment]
Both; we discovered it in prod and fixed it by downgrading to 0.8.1. I can repro in our app in both release and development builds.

**Comment by Lokeh** [comment]
Unfortunately I haven't been able to create a minimal example; our application is quite complex and it's not obvious why it works/doesn't work. What I do know is that our app does something like:

1. Gets some data, populates the re-frame app-db with data
2. Renders page with data
3. User does an action to switch what data should be shown
4. Clears out data from re-frame app-db
5. Re-fetches data, populates the re-frame app-db with data
6. Renders page with data

In reagent 0.8.1, this works fine. However in reagent 0.9.0-rc2, the error occurs on step (4) inside a re-frame subscription. It isn't expecting the data in the app-db to be empty.

I have a couple hunches, but I'm either confused why this is broken in 0.9.0; or I'm confused why it _works_ in 0.8.1.

**Comment by Deraen** [comment]
I've now pushed out 0.9.0-rc3. It probably won't affect this problem, but if you have time to check that ou can still reproduce the problem, it would be great help!

**Comment by mtruyens** [comment]
I can confirm this issue with 0.9.0-rc2. I have upgraded to -rc3, and will hceck whether it also happens with that version.

**Comment by mtruyens** [comment]
I have finally found a reproducible simple case of the above problem. 

(The project shows two collections of grey or yellow elements, and the scrolling position of the user is saved in a ratom when you switch the current collection. The project was created using the latest Luminus template with reagent & figwheel; the test itself is on the "About" page.)

**Reframe 8.1**
* reload the page
* click on the right button ("select collection number 1") and then on the left button ("select collection number 0") to once again show the grey elements of collection 0
* scroll to the last grey element (nr. 99)
* click on the right button ("select collection number 1") to show the collection with the yellow elements
* the "last scroll position" should now show a number like 5534
* the output in the console shows: 

rendering sub-component-a
rendering sub-component-b

_rendering collection 0_
rendering sub-component-a
rendering sub-component-b

_rendering collection 1_
unmounting sub-component-a
unmounting collection-nr  0
rendering sub-component-a
rendering sub-component-b

_rendering collection 0_
unmounting sub-component-a
unmounting collection-nr  1
rendering sub-component-a
rendering sub-component-b

_rendering collection 1_
unmounting sub-component-a
unmounting collection-nr  0
rendering sub-component-b


**Reframe 0.9.0-rc3**
Repeat the steps above. Not only will the "last scroll position" become 0 (instead of some high number), the log is also quite different:

rendering sub-component-a
rendering sub-component-b

_rendering collection 0_
rendering sub-component-a
rendering sub-component-b

_rendering collection 1_
unmounting sub-component-a
unmounting collection-nr  0
rendering sub-component-a
rendering sub-component-b

_rendering collection 0_
unmounting collection-nr  1
rendering sub-component-a
rendering sub-component-b      _<-- up to this point everything is the same_

_rendering collection 0_      _<-- rendering again!!_
unmounting sub-component-a
unmounting collection-nr  0
rendering sub-component-a
rendering sub-component-b

_rendering collection 1_
unmounting collection-nr  0
rendering sub-component-a
rendering sub-component-b

_rendering collection 1_     _<-- rendering again
unmounting sub-component-a
unmounting collection-nr  1
rendering sub-component-b
[regression error.zip](https://github.com/reagent-project/reagent/files/3957142/regression.error.zip)


[regression.txt](https://github.com/reagent-project/reagent/files/3957141/regression.txt)

**Comment by zlosynus** [comment]
We are likely experiencing the same problems, which is quite annoying. What happens to us is that we have a parent component and a child component. A change in the state should remove the component, so it should not be rendered again and only the parent component should be updated. But instead the child component is first updated and then removed by its parent component. We noticed this since it can fail the rendering when the child components throws an exception (due to the change in the data, but it should be fine since it should not get rerendered). Hoping for a fix soon.

**Comment by mtruyens** [comment]
The parent/child problem was also for me the most obvious one, because suddenly certain assumptions in the child (about certain values passed on by the parent) were no longer holding. However, in most cases I could still deal with this problem, by introducing upfront checks. 

Earlier this week, I then encountered very erratic and inconsistent behaviour, where I was unable to store the correct scrolling position (quite important for my application) when switching between "sibling" components of the same parent. 

It just happened that — unlike the other problems, which seemed to be caused by a delicate interplay of components — this scrolling position problem was easy to reproduce.

**Comment by Deraen** [comment]
Thanks!

I think I've started to uncover reason for this. I got the example simplified to this:

```clj
(defonce active-collection-nr (r/atom 0))

(defn collection
  [collection-nr]
  (println "rendering collection" collection-nr)
  [:div
   [:h1 "now showing collection nr " collection-nr]])

(defn sub-component
  []
  (println "rendering sub-component")
  [:div
   (for [collection-nr (range 2)]
     ^{:key (str "b-" collection-nr)}
     [:button
      {:on-click #(reset! active-collection-nr collection-nr)}
      (str "select collection number " collection-nr)])

   ^{:key @active-collection-nr}
   [collection @active-collection-nr]])

(defn bug-example []
  ^{:key @active-collection-nr}
  [sub-component])
```

and I used this to create failing test case:

```clj
(deftest issue-462-test
  (when isClient
    (let [val (r/atom 0)
          render (atom 0)
          a (fn [nr]
              ; (js/console.log "rendering a")
              (swap! render inc)
              [:h1 "Value " nr])
          b (fn []
              [:div
               ^{:key @val}
               [a @val]])
          c (fn []
              ^{:key @val}
              [b])]
      (with-mounted-component [c]
        (fn [c div]
          (is (= 1 @render))
          (reset! val 1)
          (r/flush)
          (is (= 2 @render))
          (reset! val 0)
          (r/flush)
          (is (= 3 @render)))))))
```

My hunch is that this is related to mount order recording, which is used to rerender components after ratom changes. Wrong order here could tell React to first force update the children, and then the parent, and because that changes they key of children, it will have to render children again.

**Comment by Deraen** [comment]
DidMount (or WillMount) aren't called for all the components,
only those that did change.
Previously (WillMount) numbers where given to components before their children.
Now numbers are given to children first.

This breaks case where only the chilren are rerendered, as they will now have bigger ordering numbers,
their changes will now run before their parents,
and can in some cases (parent changes React key)
cause the children to be rendered multiple times.


0.8.1

c 1 > b 2 > a 3

a rerendered

c 1 > b 2 > a 4

b rerendered

c 1 > b 5 > a 6

0.9.0

c 3 > b 2 > a 1

a rerendered

c 3 > b 2 > a 4

^BROKEN

b rerendered

c 3 > b 6 > a 5

^BROKEN

**Comment by Deraen** [comment]
@Lokeh @mtruyens Please test https://github.com/reagent-project/reagent/pull/468

**Comment by mtruyens** [comment]
Thanks for this commit!

At first sight, the problem seems indeed to be solved in my (fairly large & complex) project. I will give it some more testing during the rest of the week.

**Comment by Deraen** [comment]
I've pushed out rc4 with the fix. I'm quite confident this takes care of the issues, now that I understand what was happening, and the implementation is now much closer to what was used in previous releases. Still, React componentWillMount and constructor could work differently in some cases that could affect mount ordering which is used for RAtom updates, so reports are welcome.
