### ISSUE TITLE
Allowing lifecycle metadata on inner component fns

### ISSUE THREAD

**Issue by ptaoussanis** [reagent-project/reagent#47]
Hi Dan, hope you're well!

Think this might be clearer to explain with an example. It's currently possible to write something like:
```clojure
(with-meta
  (fn outer-component [arg1 arg2]
    (let [local-state (atom {})] ; Perform setup, etc.
      (fn inner-component [arg1 arg2]
        [:div (str arg1 "," arg2 "," @local-state)])))
  {:component-did-mount (fn [this])})
```

This works, but the :component-did-mount fn has to do w/o access to `local-state`.

It's be nice to support something like this:
```clojure
(fn outer-component [arg1 arg2]
  (let [local-state (atom {})] ; Perform setup, etc.
    (with-meta
      (fn inner-component [arg1 arg2]
        [:div (str arg1 "," arg2 "," @local-state)])
      {:component-did-mount
       (fn [this]
         ;; Has access to local-state (but doesn't currently trigger)
         )})))
```

I.e. by allowing lifecycle metadata on the inner component, we gain the ability to share local setup state with the mount fn.

Does that make sense?
Think it'd be feasible?
Any downsides?
Would a PR be welcome?

Thanks a lot! No urgency on this at all, know you've been busy.

Cheers :-)

**Comment by mike-thompson-day8** [comment]
I've created a Wiki page, so we have an explanatory resource to point to when this issue comes up again:  https://github.com/reagent-project/reagent/wiki/Creating-Components 
Any edits or clarifications on that Wiki page are most welcome.

**Comment by seancorfield** [comment]
Great wiki page @mike-thompson-day8 but it makes me wonder whether adding `:component-render` as an alias for `:component-function` (and perhaps deprecating the latter) would make usage more obvious.

In fact, why not use `create-component` and have it use aliases for all the lifecycle methods that drop the `component-` prefix? It would be less typing than the current approach and more consistent (especially since you are creating a _component_ not a _class_?).

**Comment by holmsand** [comment]
Doesn't `:component-render` risk getting confusing? After all, `:render` renders a component as well...

How about `:function-render`, to (hopefully) highlight that this thing is called using "function conventions", rather than the boring old React way?

Or `:fn-render`? Or something better...?

**Comment by gadfly361** [comment]
:+1: `:function-render` (but i think any of the suggestion are an improvement over `:component-function`)

**Comment by skrat** [comment]
Well, anything with `function` in it is a face palm. Let's see, what about...

    (defn my-component
      [x y z]  
      (let [some (local but shared state)
            can  (go here)]   
         (reagent/create-class
           {:did-mount  #(println "Did mount")
            :will-mount #(println "Will mount")
            :render
              (fn [x y z]
                [:div (str x " " y " " z)]))}))

Because, `component-` prefixes are pointless.

**Comment by seancorfield** [comment]
I'm suggesting mapping from "Reagent keys" which we choose and control to "React keys" rather than just slavishly following the React lifecycle names as keys.

As noted on @mike-thompson-day8 wiki page:

"Its a trap to mistakenly use `:render` because you won't get any errors, except the function you supply will only ever be called with one parameter, and it won't be the one you expect."

I think we can remove that mistake by making `:render` do the right thing by having `create-class` (or, better, `create-component`) map `:render` to what users would intuitively expect, as @skrat shows in an example.

Having to repeatedly type `:component-` for no good reason seems counter to the otherwise simple and elegant approach Reagent takes elsewhere.

**Comment by holmsand** [comment]
@skrat and @seancorfield Naming is hard :)

I agree that `:render` should have been the one with Reagent-style arguments, but I think it would be a bit nasty to change it now (without any way of issuing a warning). 

As you say @seancorfield, switching to something like `create-component` with a new argument for `:render` is probably the way forward (`create-class` could then be deprecated with a suitable warning).

In the meantime, the-thing-that-is-now-component-function must be called something, and since there seems to be universal hate for the previous alternatives, how about these:

- `:reagent-render` (at least it sort of says what it does...)
- `:run` (short and descriptive, but maybe differs too much from the normal React terminology?)

That would maybe be a temporary solution anyway, if we go with `create-component` or some such, but it  would sure be nice to get a 0.5.0 out of the door :)

**Comment by mike-thompson-day8** [comment]
+1 for `reagent-render`

**Comment by holmsand** [comment]
Reagent 0.5.0-alpha3 now supports `:reagent-render`. I still think that `create-component` is a good idea, though, but after 0.5.0.

**Comment by johanatan** [comment]
I kinda like the `with-meta` syntax better. Any reason why a change can't be made to allow it on inner components?

**Comment by yogthos** [comment]
Actually, I believe this should still work if you wrap the inner component with a vector:

```clojure
(fn outer-component [arg1 arg2]
  (let [local-state (atom {})] ; Perform setup, etc.
    [(with-meta
       (fn inner-component [arg1 arg2]
         [:div (str arg1 "," arg2 "," @local-state)])
       {:component-did-mount
        (fn [this]
          ;; Has access to local-state (but doesn't currently trigger)
          )})]))
```

**Comment by kangbb** [comment]
I have a problem with `create-class` - whether the `set-state` works for updating component? I have use it in `:render`, it doesn't trigger rerender.

**Comment by kangbb** [comment]
> Actually, I believe this should still work if you wrap the inner component with a vector:
> 
> ```clojure
> (fn outer-component [arg1 arg2]
>   (let [local-state (atom {})] ; Perform setup, etc.
>     [(with-meta
>        (fn inner-component [arg1 arg2]
>          [:div (str arg1 "," arg2 "," @local-state)])
>        {:component-did-mount
>         (fn [this]
>           ;; Has access to local-state (but doesn't currently trigger)
>           )})]))
> ```

I have try your answer, actually, pass `arg1` `arg2` to `inner-component` will make them undefined. If want work, we should do:
```clj
(fn outer-component [arg1 arg2]
   (let [local-state (atom {})] ; Perform setup, etc.
     [(with-meta
        (fn inner-component []
          [:div (str arg1 "," arg2 "," @local-state)])
        {:component-did-mount
         (fn [this]
           ;; Has access to local-state (but doesn't currently trigger)
           )})]))
```
But this is against with `Form-2` that how to create a component, which is recommended by officials'.
