### ISSUE TITLE
Find better name for "Compiler" object

### ISSUE THREAD

**Issue by Deraen** [reagent-project/reagent#495]
In Reagent, the Hiccup-style markup is converted to React element calls in runtime, so compiler is not the best name to describe this. But I don't like Interpreter either as name for this. "Options" also feels confusing, because the object really contains a few methods and maybe some internal state (cache).

- The name shouldn't be to connected to the implementation, runtime vs. macro compilation time
- Shouldn't be confusing with React or ClojureScript terms

**Comment by victorb** [comment]
Calling out the most obvious first: `converter`, `adapter` or `translator`. Very overloaded terms in programming though, so might be best to avoid.

Otherwise, more unique but still descriptive would be something like `elementifier`. I guess something that could be very explicit about it's meaning would be `markup->elements` / `markup->elements-fn` or similar.

**Comment by davidpham87** [comment]
Some candidate popping up in my mind: `hiccup->elements`, `hiccup->elems`.

**Comment by jeroenvandijk** [comment]
`compiler` sounds like a good name to me
