### ISSUE TITLE
with-let hides the original exception if it caused another one down the line

### ISSUE THREAD

**Issue by p-himik** [reagent-project/reagent#525]
Consider this code:
```
(defn app []
  (reagent/with-let [a [1]
                     _ (throw (js/Error. "Hello there"))
                     n (count a)]
    [:span (nth a (dec n))])
```

Rendering it result in a long call stack that doesn't have the original `"Hello there"` error at all - all it has is a `Uncaught Error: No item NaN in vector of length 1` error that makes things really confusing, especially when `throw` is in some function that's not immediately visible to the reader of the `app` component.

**Comment by Deraen** [comment]
This is quite interesting case.

Due to how Ratoms and with-let works, the body, "render" code, is evaluated even if a let binding throws error. I think because after initial render, the binding value is not used (here `(throw ..)` call), and instead the value is just retrieved from the reaction.

In this case it means that `n` is undefined because last binding form is not evaluated, but then render code tries to use that binding.

Not sure if it would make sense to catch errors in binding values, and then store them in with-let reaction state, and re-throw from render, ensuring the render code doesn't run if bindings has errors...

**Comment by Deraen** [comment]
Ha, I found a good solution after some tinkering.

No need to catch and store errors, just run the binding value expression again if the with-let ratom doesn't have the value for that binding yet set, and this will ensure further with-let calls with trigger the error again.
