### ISSUE TITLE
Support for animations

### ISSUE THREAD

**Issue by redalastor** [reagent-project/reagent#55]
Reactjs has an animation addon that would be neat idiomatically use in reagent:

http://facebook.github.io/react/docs/animation.html

The problem solved by the addon is that if you CSS animate your exit transition the DOM component must *not* be removed until the animation is done, otherwise it just blinks out of existence.

**Comment by JulianLeviston** [comment]
This would be pretty awesome. I wonder if there has been any further movement on this?

**Comment by jcreedcmu** [comment]
This appears to be entirely usable as long as you use `cljs/react-with-addons "0.13.1-0`. As of https://github.com/cljsjs/packages/commit/e82b19e8187a21c9ef177c487b6b043755e06f31it includes React.addons.CSSTransitionGroup. Since reagent 0.5.0 is still apparently on 0.12.5-2, I made a fake reagent 0.5.1 by cloning reagent-project/reagent, replacing `[cljsjs/react "0.12.2-5"]` with `[cljs/react-with-addons "0.13.1-0"]` in its project.clj, doing `lein jar` and putting the resulting jar in `~/.m2/repository/reagent/reagent/0.5.1/reagent-0.5.1.jar`, then changing my own project's dependencies to ask for `cljs/react-with-addons "0.13.1-0"` and `reagent 0.5.1`.

Having done that, the following clojurescript code does nice list item insertion and removal animations:

```cljs
(defn without-nth [seq n]
  vec (concat (subvec seq 0 n) (subvec seq (+ 1 n))))

(def css-transition-group
  (reagent/adapt-react-class js/React.addons.CSSTransitionGroup))

(def style "

li {
  background-color: #44ee22; padding: 10px; margin: 1px; width: 150px;
  border-radius: 5px;
  font-size: 24px;
  text-align: center;
  list-style: none;
  color: #fff;
  height: 2em;
  line-height: 2em;
  padding: 0 0.5em;
  overflow: hidden;
}

.foo-enter {
  height: 0;
  transition: height 0.27s ease-out;
}

.foo-leave {
  height: 0;
  transition: height 0.27s ease-out;
}

.foo-enter-active {
  height: 2em;
  opacity: 1;
}")

(defn list-comp [items]
   [css-transition-group {:transition-name "foo"}
       (map-indexed (fn [i x] ^{:key x} [:li (str "List Item " x)]) @items)  ])

(defn main-comp []
  (let [items (atom ["a" "b" "c"])
        next-item (atom 0)
        adder (fn [position]
                (fn [e]
                  (do (swap! items #(vec (let [[bef aft] (split-at position %)]
                                           (concat bef [@next-item] aft))))
                      (swap! next-item inc))))
        deleter (fn [position]
                  (fn [e] (swap! items #(vec (without-nth % position)))))
        _ (js/setTimeout (adder 0) 300)
        _ (js/setTimeout (adder 2) 700)
        _ (js/setTimeout (adder 5) 1100)
        _ (js/setTimeout (deleter 0) 1600)
        _ (js/setTimeout (deleter 2) 2000)
        _ (js/setTimeout (deleter 2) 2400)]
    [:div
     [:button {:on-click (adder 0)} "add"]
     [:button {:on-click (deleter 0)} "remove"]
     [:style style]
     [:ul
      [list-comp items]]
     ]))
```

**Comment by jcreedcmu** [comment]
I was reluctant to make a pull request simply pulling in `cljs/react-with-addons "0.13.1-0"`, though, since I didn't know if that would undesirably cause the javascript output of reagent projects to be larger, because of the addons --- although I see https://github.com/cljsjs/packages/blob/master/react/README.md saying that `-with-addons` provides the exact same .jar?

**Comment by jcreedcmu** [comment]
Aha! Empirically, if I use `[cljsjs/react-with-addons "0.13.1-0"]` in my own project, and `[cljsjs/react "0.13.1-0"]` in reagent, everything seems to work.

**Comment by yogthos** [comment]
@gadfly361 might be an idea to create a recipe for this :)

**Comment by gadfly361** [comment]
@yogthos Agreed!

@jcreedcmu Would you be interested in creating a [reagent-cookbook](https://github.com/reagent-project/reagent-cookbook) recipe for this?

**Comment by matt-loyal3** [comment]
@yogthos Just revisited this and should have recipe in the next couple of days.

**Comment by gadfly361** [comment]
@yogthos Just revisited this and should have recipe in the next couple of days.

**Comment by yogthos** [comment]
@gadfly361 fantastic :)

**Comment by JulianLeviston** [comment]
<3

**Comment by gadfly361** [comment]
https://github.com/reagent-project/reagent-cookbook/tree/master/recipes/ReactCSSTransitionGroup

**Comment by marcloyal3** [comment]
Reflex makes sense. So does freactive. Assuming neither uses React or virtual dom concept. 

I think most people are weak minded and never question the hype .. If they feel "smarter" people are promoting something then it must be good. Happened with Angular and now with React. 

Again, why do you need a virtual dom if you can build DOM components or Canvas or WebGL components that react to scoped changes in state? They can so so so very very easily with one line of code have their own mount/unmount callbacks like in D3 there is enter() and exit()

I am dumbfounded

**Comment by marcloyal3** [comment]
Good job @gadfly361 

Could also be done in mount/unmount cycles, so I wonder what advantages this has over doing it in lifecycle callbacks.

**Comment by dmkolobov** [comment]
On a related note, does anyone know if stateful animation via `ReactTransition` group is supported? 

I'm trying to build an animated accordion-like component, and I need to set the `max-height` to a know value to prevent animation delay when the content collapses. Based on my understanding of the React docs, the baked in 'CSSTransitionGroup' is insufficient for this.

So I made two components:

```clojure

(defn accordion-content
  [content]
  (reagent/create-class
   {:component-will-enter 
     (fn [cb] (println "entering")}) (cb))
    :component-did-enter
      #(println "entered")
    :component-will-leave ;; set max-height here
      (fn [cb] (println "leaving") (cb))
    :component-did-leave
      #(println "left")}))

(def transition-group
  (reagent/adapt-class js/React.addons.TransitionGroup))

(defn accordion
  [expanded content]
  [:div
   [transition-group
    {:transition-name "accordion-expanding"}
    (map-indexed (fn [idx c] ^{:key idx} c)
                 (when @expanded? [accordion-content content]))])
```

Per the docs, whenever children are added/removed to the group, the special lifecycle methods above are invoked on the child. The lifecycle methods are never called in my example.

Am I missing something here? I know that reagent wraps each non-native component in another one. Is it possible that the `accordion-content` is wrapped in some component which intercepts the lifecycle invocations, or prevents the transform group from working properly?

**Comment by JulianLeviston** [comment]
@dmkolobov Isn't it just because you're missing any kind of render in your class? Maybe it'd be good to read https://github.com/Day8/re-frame/wiki/Creating-Reagent-Components - but perhaps *I'm* missing something :) H2H

**Comment by dmkolobov** [comment]
Whoops, @JulianLeviston forgot to add in the example, it was present in when I ran the code. Fixed in the example.

**Comment by dmkolobov** [comment]
And to clarify, the `accordion-content` component renders and disappears whenever the value of `expanded?` changes, as expected. Regular lifecycle methods are called on it, the special transition group child ones are not.

**Comment by JulianLeviston** [comment]
I don't understand what you're map-indexing over... it looks like you're trying to map index over a vector with the accordion-component function and the content in it. Very confusing! But... you're probably trying to do something else... this is probably a *terrible* place to discuss this. I'll be on IRC in a minute if you like.

**Comment by AlexanderWingard** [comment]
@dmkolobov
I'm interested, did you ever get this to work?

**Comment by Reefersleep** [comment]
@dmkolobov I'm interested in this as well. 

And regarding @GetContented 's question re: `map-index`, I gather that you're adding individual, unique `:key`s to your coll in order to satisfy `react`s need to distinguish between individual elements in a list. It's a common enough pattern. I do, however, fear that it might interfere with the intent of the `:component-will-enter` hook and the other `ReactTransitionGroup` hooks, as I believe that they actually depend on the `:key`. I can describe it with an example:
A coll of 10 items wrapped in a `ReactTransitionGroup` with `:component-will-leave` hooks for each element is mounted. Each element in coll has a `:key` distinguishing it from all the other elements. The `:key` is the an integer denoting each item's index in the collection, ie `0`, `1`, `2`... `7`, `8`, `9`. 
Now click a button in the UI, intendint to remove the 5th element in the list (with index/`:key` 4). `ReactTransitionGroup` now wants to do a diff between the list before the intended removal and after the intended removal so it can determine whether to call lifetime hooks on the item intended for remova. But the diff shows that the item of index `4` has `:key` 4 after the intended removal, just as before - `ReactTransitionGroup` is happily unaware that the items in question are actually different, and only look alike to _it_ because they have the same `:key`, since keys are just allotted by index (with `map-index`).

This is just me trying to extract info from various experiments I did in trying to get the lifecycle hooks working for reagent, so it's guesswork based on experiments I did a month ago, but I think I did learn that the `:key` should uniquely identify the item.

This did NOT enable me to get the additional lifecycle hooks working, but I think it was crucial to even get the high level API working properly.

I think, however, that it was @AlexanderWingard who found out that `react-transition-group` seems to strip any additional lifecycle hooks (and maybe other stuff) from a component before rendering it, though I was unsure from the context whether this was the exact conclusion to be derived from the code. The conclusion doesn't seem to make sense, in that the lifecycle hooks are supported in vanilla `react`...
https://github.com/reactjs/react-transition-group/blob/v1.1.3/src/TransitionGroup.js#L226

**Comment by Reefersleep** [comment]
Maybe it's a case of `reagent`s ` `custom-wrapper` function not including `case` entires for `ReactTransitionGroup`s additional lifecycle hooks? And thus, the functions associated with those hook keywords are called wrongly or not at all?

**Comment by Deraen** [comment]
@Reefersleep If `custom-wrapper` doesn't return a wrapped function, Reagent will use the provided function as is:

- https://github.com/reagent-project/reagent/blob/d76eaba97c4e79cbe251d2d13fac4ae1dd23c58c/src/reagent/impl/component.cljs#L205
- https://github.com/reagent-project/reagent/blob/d76eaba97c4e79cbe251d2d13fac4ae1dd23c58c/src/reagent/impl/component.cljs#L242
- https://github.com/reagent-project/reagent/blob/d76eaba97c4e79cbe251d2d13fac4ae1dd23c58c/src/reagent/impl/component.cljs#L261
- https://github.com/reagent-project/reagent/blob/d76eaba97c4e79cbe251d2d13fac4ae1dd23c58c/src/reagent/impl/component.cljs#L267

So the function should be called.

**Comment by AlexanderWingard** [comment]
Here is my workaround where I set the callback without reagent: https://github.com/AlexanderWingard/reagent-with-transition-group-example

**Comment by Deraen** [comment]
New issue should be created about not being able to use ReactTransitionGroup.
