### ISSUE TITLE
JS Error upon running the "simple" example

### ISSUE THREAD

**Issue by taylorlapeyre** [reagent-project/reagent#57]
After compiling the clojurescript and opening the `example.html` file in Google Chrome (I have not tested other browsers), I am met with the following error:

![a336_zx13qsffraznz2hu8vsuruh361tolmlkdbmroc](https://cloud.githubusercontent.com/assets/1610503/4695022/6d6d64e8-57e0-11e4-9003-c7d89921d679.png)

Steps to reproduce:

1. Clone holmsand/reagent
2. `cd` into `reagent/examples/simple`
3. run: `make`
4. After clojurescript successfully compiles, run: `open index.html` in a different terminal
5. Open browser and inspect the console.

**Comment by Gregg8** [comment]
Have tried to reproduce this using your steps but failed to see any errors in three tries:

- Grabbed the [0.4.3 repo](https://github.com/reagent-project/reagent/archive/v0.4.3.zip) as it was when the issue was reported. Works fine in my Chrome 40 under Windows 8.1.
- Pulled the current [holmsand repo](https://github.com/holmsand/reagent). No errors.
- Pulled the current [reagent-project repo](https://github.com/reagent-project/reagent). No errors.

Can anyone else reproduce? This seems closeable now.

**Comment by taylorlapeyre** [comment]
Seems to be fixed now! Closing.
