### ISSUE TITLE
shadow-cljs emits a warning when using with-let

### ISSUE THREAD

**Issue by timmw** [reagent-project/reagent#585]
Similar to [this](https://github.com/reagent-project/reagent/issues/420) issue reported a while ago.

When using `with-let` I get the following warning.

> Cannot infer target type in expression (. with-let11498 -generation)

Possibly due to a missing type hint?

I've made a minimal reproductrion of the issue [here](https://github.com/timmw/reagent-extern-warn).

reagent `1.1.1`
shadow-cljs `2.20.17`

Edit: This warning doesn't occur when using shadow-cljs 2.20.16 or below. Seems to be a result of [this](https://github.com/thheller/shadow-cljs/blob/master/CHANGELOG.md#22017---2023-01-04)

> 2.20.17 - 2023-01-04
> [ [f35fa](https://github.com/thheller/shadow-cljs/commit/f35faabd94add4bc7a48df8a80483d6f9e5f6636) ] add externs inference warnings for destructured bindings

**Comment by grav** [comment]
(not original poster) Seems to disappear when I downgrade Shadow-CLJS to `2.20.14`

**Comment by thheller** [comment]
I can confirm that the linked shadow-cljs change is the cause of this. The commit changed it so that proper inference warnings are emitted for `let` bound names. Although no externs are necessary in this particular case the warning is still "correct".

My suggestion would be to move this entire block of code into a helper function

https://github.com/reagent-project/reagent/blob/e67d4f8804c109868469d6e81ecd7184cf707575/src/reagent/ratom.clj#L62-L67

So something like

```clojure
(defn check-generation! [^clj v]
  (when-some [^clj c reagent.ratom/*ratom-context*]
    (when (== (.-generation v) (.-ratomGeneration c))
      (d/error "Warning: The same with-let is being used more "
        "than once in the same reactive context."))
    (set! (.-generation v) (.-ratomGeneration c))))
```

and the macro just emits a function call there. This reduces the amount of code generated for every `with-let` and doesn't need extra hinting in the macro itself.

**Comment by scarytom** [comment]
Would it be in any way useful if someone took @thheller's suggested change and made a pull request?  I'll volunteer to do that if it helps move things along, but if that would just get in the way of @Deraen then I'll leave things be.
