### ISSUE TITLE
Remove Cursors Code?

### ISSUE THREAD

**Issue by mike-thompson-day8** [reagent-project/reagent#77]
Sean kindly agreed put the Cursor Code into its only library.  

But the code remains in the reagent library:
   https://github.com/reagent-project/reagent/blob/master/src/reagent/ratom.cljs#L98-L177
   https://github.com/reagent-project/reagent/blob/master/src/reagent/core.cljs#L202-L226

Should be removed to avoid duplication?

**Comment by seancorfield** [comment]
@holmsand I'm looking at incorporating some of (or all of) your changes to `RCursor` into the standalone library - so that it could be removed from Reagent core - and I notice you've added `setf` and `reaction` as optional, undocumented, arguments. Could you explain what those would be used for?

It seems that if the optimizations from Reagent's version of `RCursor` are to be folded into the standalone library, it would need to become dependent on Reagent (which I don't mind, but it currently has no dependencies) which would limit its use outside of Reagent projects.

**Comment by seancorfield** [comment]
As a corollary to that comment: if we do, ultimately, decide to make the Reagent version the "one true cursor" then we should at least fold @Frozenlock's enhancements into the core version.

**Comment by Frozenlock** [comment]
As per https://github.com/reagent-project/reagent/issues/76
