### ISSUE TITLE
Remove Assert?

### ISSUE THREAD

**Issue by mike-thompson-day8** [reagent-project/reagent#81]
I use the macro `reaction` [see here](https://github.com/reagent-project/reagent/blob/master/src/reagent/ratom.clj#L3-L5)   

But, depending on the way I later dereference the returned `Reaction`,  I can sometimes get the error "Reaction derefed outside auto-running context"  [from here](https://github.com/reagent-project/reagent/blob/master/src/reagent/ratom.cljs#L250-L251)

At that point, I can work around the problem by cheating and using the macro `run!` instead (code is next to `reaction`).   This macro (run!) does not trigger the problem because it uses the parameter  `:auto-run true` when calling `reagent.ratom/make-reaction`.

**My question:**  should that assert  be removed.  Seems unnecessary.  

I can certainly work around this issue (use my own macro).  So it is not a shop stopper.  But it seems an unnecessary check.   And it feels like a hack to have to use `auto-run true` to work around it. 

**Later:**  I'm aware that this check is in there to warn people who might be doing something crazy, but I'm not doing anything crazy, honest, so I believe we need (1) a way to optionally silence the `assert` (like it is when you use run!) or (2) removal of the `assert` completely.

**Comment by mike-thompson-day8** [comment]
Below is @holmsand initial response, copied across from #76 

>  #81 is a bit more subtle. I think that just removing the assert may lead to memory leaks (since watches are added and never removed), so that needs to be thought through, and tested. But I definitely agree that it must be done.

**Comment by mike-thompson-day8** [comment]
@holmsand  You've made me nervous now. :-) About 5 months ago, I spent a bit of time  proving to myself that I wouldn't have a memory leak problem.  I can remember being fairly paranoid and careful, but you have me worried again.  I'll check again.

I hesitate to burden you with context, but you might be interested to understand why I'd like this. I've designed a "framework" around Regent for writting SPAs: https://github.com/Day8/re-frame.

These sort of reactions are pretty central to re-frame.

**Comment by holmsand** [comment]
@mike-thompson-day8 Being slightly paranoid here is a virtue, I guess. I'm a bit nervous myself about changing Reaction – it is probably a bit too fancy for its own good :)

Btw re-frame looks really cool. Just some context on my thinking: I haven't pushed use of `Reaction` myself because it has (at least) three problems (even if it is quite powerful and general, at least until you shoot yourself in some extremity):

- `Reaction`s don't have any concept of equality (and they cannot, since they rely only on functions/closures to be useful). Therefore they are inefficient if they are created in a parent component, and passed to a child.

- They (re-) run synchronously when a parent `RAtom`/`Reaction` changes. That may lead to hard-to-debug problems, especially performance-wise, if you do something stupid.

- If you use a "top-level" Reaction (i.e one where auto-run isn't `nil`) you have to remember to "unsubscribe" (i.e dispose, in this case). And I hate having to remember to unsubscribe/destroy/cleanup stuff :)

So, more thinking about a "safe and efficient subset" (or subsets) of what Reaction does (and a more friendly API) is very welcome, since it is now definitely in the "powerful and dangerous" category...

Re the problem at hand: I'll have another look myself at what I think may be the problem.

**Comment by mike-thompson-day8** [comment]
@holmsand  I can comment on one of your three concerns:  memory leaks ... 

I created a tiny demo program which thrashes `reaction`  in a `subscription` like manner.  Inspecting via Chrome dev tools, I can see no memory leaks. 

I've experimented using both `reaction` and `run!`, and both seem clean. 

Having said that, I'm still a bit of a browser -tech neophyte, so I might have used Chrome devtools wrongly, maybe. Seems unlikely. 

I think that the key bit of code is this:
https://github.com/reagent-project/reagent/blob/master/src/reagent/ratom.cljs#L195-L196

When a `reaction` notices that it has no watches, it disposes itself.

**Comment by holmsand** [comment]
@mike-thompson-day8 Thanks for doing that! I'll take a look myself shortly – I feel a bit more confident now...

**Comment by holmsand** [comment]
@mike-thompson-day8 I'm happy to say that the pesky assert is now gone in master...

It turned out to be a little tricky – but the result is quite pleasing, I think. `Reaction` is now flexible enough that `cursor` is built entirely on top of it. That, in turn makes the new `cursor` a lot more flexible than before (it can use arbitrary setters/getters).

**Comment by mike-thompson-day8** [comment]
@holmsand  Looking good!  Many Thanks.  After you release, I'll announce re-frame.
