### ISSUE TITLE
Correct reporting of "missing key" warning

### ISSUE THREAD

**Issue by Skinney** [reagent-project/reagent#87]
When you have a list of elements in React which are missing :key attributes, React will issue a warning that this could be inefficient. This warning usually indicates where in your code you make a mistake, but currently, this will always point to a function in reagent, which doesn't give you a lot of information on where you can fix your code.

Is it possible to make reagent report the correct place, or at least the datastructure, where you are missing :key?

**Comment by mike-thompson-day8** [comment]
This issue has multiple heads.  Another version of it:  if I ever mistakenly put  a "[]"  in the hiccup the error message produced does not identify where it occurred. 

Can we attach meta-data to the renderer functions perhaps, and have that reported?

**Comment by holmsand** [comment]
I totally agree that a better diagnostic message would be great. Unfortunately, that message comes from React, and if Reagent produces one as well that might be even more confusing...

Do you, by any chance, have a good code example handy, where the message becomes confusing? Perhaps that would trigger some improvement ideas.

**Comment by Skinney** [comment]
The problem is when I don't know what code triggers the following warning: "Each child in an array should have a unique "key" prop. Check the render method of reagent3. See http://fb.me/react-warning-keys for more information."

reagent3 doesn't tell me where I'm going wrong :/

**Comment by holmsand** [comment]
@Skinney The "reagent3" name is a generated `displayName`, that is created because there wasn't any (presumably because you used `create-class`?).

Otherwise Reagent uses the name or displayName fields of the render function to create a displayName for the component. You can also provide `:display-name "foo" to `create-class`, or use a named render function (`:render (fn foo [] "hi")`)

That is obviously not ideal, but unfortunately it's a bit hard to come up with better alternatives.

The only one I could think of would be to turn `create-class` into a macro, and use something like <package-name>:<line-number> for displayName. At least that would be better than "reagent3"...

I *think* it should be possible to add a macro transparently with the new version of clojurescript, but I haven't looked at that more closely.

@mike-thompson-day8 The `[]` warning is similar, but a different issue. That warning comes from Reagent directly, and didn't even use `displayName`. It should do that now, however, with the code in master.

I've tried to revamp most of the warnings emitted by Reagent to display `displayName`, and they now use `console.warn` to make them stand out a bit more.

**Comment by Skinney** [comment]
I don't use `create-class`. I pass functions like these to render-component.

```clojure
(defn sample []
  (let [local-state (r/atom {})]
    (fn []
       [:div "something"])))```

**Comment by holmsand** [comment]
@Skinney A reproducible example of code that triggers the warning would be great...

**Comment by Skinney** [comment]
That's why I've opened this issue, I have no idea what particular code triggered the warning :P
My project is open source though, and you can see the code at Skinney/masters-of-cthulhu

**Comment by mike-thompson-day8** [comment]
@Skinney: I'm wondering if perhaps you are supplying a key BUT that somehow that key is nil?  A nil key is the same as not supplying one.

**Comment by holmsand** [comment]
@Skinney In Reagent 0.5.0-alpha3 the warning should be a bit more informative. Reagent now tries harder to find a meaningful name for the component (getting names from ifns, etc.), and also prints out the offending `seq` itself. The downside is that now you'll get two warnings, one from Reagent and one from React, but I hope that is still an improvement.

**Comment by Skinney** [comment]
Sorry, the last week has been a killer. I'll look into this tomorrow and try to answer you both :)

**Comment by Skinney** [comment]
The new warning is a big help :)

**Comment by boxed** [comment]
I have the same issue of having trouble finding the problem. It seems to me that if some keys aren't unique, the error message should be able to at least tell me two keys that are the same!
