### ISSUE TITLE
Upgrade dependency to cljs 2723 and leverage new JS lib packaging?

### ISSUE THREAD

**Issue by seancorfield** [reagent-project/reagent#90]
The changes in 2723 make it possible to simply `require` JS libraries as if they were cljs, as long as they've been packaged correctly and published to Clojars / Maven (as React and React-with-add-ons have via David Nolen). No need for a separate JS include in development (2723 works with `:none`), no preamble needed etc.

See https://groups.google.com/d/msg/clojurescript/pJ_EYHkYAUs/mLi8XfiQxZsJ for more details of 2719 and 2723.

**Comment by Frozenlock** [comment]
If I understand correctly, we still need to load the JS libraries in the html document when using `:optimizations` `:none` (Figwheel).

```clj
<pandeiro> the latest cljs foreign libs feature doesn't address the multiple
	   script tags necessary with :optimizations :none, right?
								        [13:17]
<dnolen> pandeiro: no that's a different problem  [13:19]
<dnolen> pandeiro:
	 http://dev.clojure.org/jira/browse/CLJS-851?focusedCommentId=37550#comment-37550
								        [13:26]
<dnolen> pandeiro: solving that problem is very low hanging fruit now
```

**Comment by city41** [comment]
I think that is referring to

```
<script src="blah/goog/base.js"></script>
<script src="blah/core.js"></script>
<script>goog.require("blah")</script>
```

**Comment by seancorfield** [comment]
I updated this ticket in light of build 2723 addressing the `:optimizations :none` issue.

**Comment by city41** [comment]
Looks like it should now be at least 2725 to fix a Node bug: https://groups.google.com/d/msg/clojurescript/pJ_EYHkYAUs/6gDu0e7YeaIJ

**Comment by seancorfield** [comment]
And it's 2727 now :)

**Comment by Skinney** [comment]
CLJSJS has a package for react available, seems you just have to add it as a dependency and :require it.

**Comment by peeb** [comment]
^^^

Yes, `om` is now using the `cljsjs/react` dependency as well.

**Comment by Skinney** [comment]
I'll create a PR for this issue tonight :)

**Comment by holmsand** [comment]
@Skinney No need: I *think* I got the whole thing working now. If you could take a look, and do some testing with `master`, that would be great.

We should probably remove the packaged React completely: that will trigger a build error when people update, thus avoiding double React inclusions.

**Comment by Skinney** [comment]
It looks about right. If I understand this correctly though, because a proper externs.js file is provided in CLJSJS, you don't need your interop.clj macros anymore, and you shouldn't need that vendored react either :)

**Comment by city41** [comment]
Does this affect using react-with-addons? If I later require `cljsjs/react-with-addons`, then I assume that replaces the global React, but do you end up with two copies of React in your final JS output?

**Comment by holmsand** [comment]
@Skinney Thanks! You're right in principle about the interop.clj macros, but I still want to use them. :) 

Having Reagent work without the proper externs makes it a lot easier to load React separately (e.g from a CDN,  using a different version, etc). And I need the macros anyway on the demo site, since I want to use node.js when generating the site – without having to care about externs.

Also: I absolutely hate debugging broken externs :)

I totally agree about the bundled React, though, and some other old cruft in e.g inteorp.clj.

@city41 You should be able to specify that you don't want `cljsjs/react` by using `[reagent "0.5.0" :exclusions [cljsjs/react]]` in `:dependencies`. Then you ought to be able to use `cljsjs/react-with-addons` instead, or supply React in any other way you want.

**Comment by city41** [comment]
excellent, thanks @holmand, I still have much to learn.

**Comment by holmsand** [comment]
FYI: Reagent 0.5.0-alpha3 uses `cljsjs/react` as a dependency, including in all the examples.

Closing this.
