### ISSUE TITLE
Component does not trigger re-render if atom is within `for` macro

### ISSUE THREAD

**Issue by zarkone** [reagent-project/reagent#91]
Of course, this is not because Reagent itself, but in my opinion it should be mentioned somewhere in docs. 

if i write something like:

```clojure
;; sorry for possible mistakes, i simplified my real code
(defn subjects-modal [current-subject]
  (let [ch (db/get-subjects)
        subjects (atom [])]
    (go (let [evt (<! ch)] (reset! subjects evt)))
    (fn []
      [:div
       [:h3  "Choose subjects"]
       [:ul
        (for [subject @subjects]
          [:li 
           {:class (when (= (:name subject) (:name @current-subject)) "active")}
           [:a {:on-click #(reset! current-subject subject)}
            (:title @current-subject)]])]])))
```
```:li``` will not become ```.active``` after click. I guess it's because the forms with atom are evaluated inside of macro. To make in work i've added 
```clojure
(let [current-name (:name @current-subject)]
 (for ...
```

**Comment by Skinney** [comment]
It's because `for` returns a lazy data-structure, so reagent can't see that current-subject is actually being dereffed. Wrapping `for` in a `doall` forces the lazy list to evaluate, and then reagent should pick up on the changes.

I do believe this is documented somewhere, i know that at least in 0.4.3 it triggered a warning.

**Comment by zarkone** [comment]
thanks for the info! i'll try to figure out why there was no warning

**Comment by holmsand** [comment]
It should still trigger a warning (unless you're running with `:elide-asserts true`) – but it was easy to miss, since the warning was only issued once. 

With the code now in `master` the warning should be more obvious, since it is produced every time that code path is triggered, and it is now printed with `console.warn` rather than `console.log`.

If you can find an example where the warning isn't triggered at all (even in 0.5.0-alpha), I'd be interested in seeing that.

**Comment by zarkone** [comment]
I reproduce my situation and get: 
```
"Warning: Reactive deref not supported in seq in " "
```
-- seems like it's my fault, sorry >..< May be this is because i printed some dubug info that time, so  ```console.warn``` is a great idea, thanks!
