### ISSUE TITLE
Root component not refreshed by force-update-all

### ISSUE THREAD

**Issue by Gregg8** [reagent-project/reagent#94]
`force-update-all` does not refresh the root component. It does however, refresh all the children. This issue shows up under figwheel use.

To reproduce:

1. Go to this page: https://github.com/gadfly361/reagent-figwheel.
2. Follow all the instructions to get it running and connected to figwheel.
3. In `src/XXX/core.cljs` (where XXX is the project name you chose in step 2), change `(page)` so it renders something slightly different. Due to the magic of figwheel, you will notice that the GUI updates correctly to reflect your change. All good. This is because `watch-and-reload` is simply calling `(core/main)` ... a bit of a sledge hammer.
4. So edit `dev/user.cljs` and change `(core/main)` to `(reagent/force-update-all)` in the `watch-and-reload` function.
5. Refresh your browser page manually (e.g. press F5) and make a change to `(page)`. This time anything in this "root" component will not update (but other modified components would update).

`force-update-all` should refresh the root component `(page)`.

**Comment by mike-thompson-day8** [comment]
There's no easy way around this.   Calling `(core/main)` in `watch-and-reload` is the right thing to do, because it remounts the root component. Effectively, it is telling reagent that the root component has changed. 

Without this information, reagent is left with a reference to the root component (`page` in your example), and it has no way to know it has been replaced.  In effect, it retains a reference to the wrong (old) component renderer.   

The salient code is here:
 https://github.com/reagent-project/reagent/blob/600d6bbb59d1040d19fbd1e9e5d45f3d7d715bd4/src/reagent/impl/util.cljs#L136-L139

Notice that reagent remembers any root components in an atom called `roots`.  So in your example, realise that `roots` is still referring to the OLD version of `page`, not the new edited version of `page`.

@holmsand  this is a problem which is likely to bite a few people.  And, worse, it is slightly baffling and hard to explain.  I wonder if  `reagent/force-update-all` should be deprecated in favour of just `re-mounting` the root component (as the reagent-figwheel template is doing).

**Comment by holmsand** [comment]
@mike-thompson-day8 Yes, `force-update-all` is a bit tricky that way (and could certainly use some documentation...).

On the other hand, it can be useful if you want to integrate Reagent with some kind of IDE (you can for example use it with Light Table, to trigger re-rendering on eval). And it is quite nice to have one config that works for any project. Perhaps `force-update-all` should be documented with a warning: don't use this if you don't absolutely have to, or some such...

There are a couple of workarounds, that should/could also be documented: you can pass a function returning a Hiccup form, instead of the Hiccup form directly, to `reagent.core/render`. That function is re-run every time `force-update-all` is run.

You can also use the brand-new vars in recent ClojureScripts: if you call `render` with `[#'foo]` instead of `[foo]`, your `foo` will always be re-rendered as you would expect.

**Comment by mike-thompson-day8** [comment]
I think this issue can be closed

**Comment by Gregg8** [comment]
Yep, this is all well discussed and understood now.
